version: '3.8'

services:
  web:
    image: tailor-inventory-app:latest
    container_name: tailor-nextjs-app
    restart: always
    ports:
      - '3001:3000'
    env_file:
      - .env
    networks:
      - tailor-network

networks:
  tailor-network:
    driver: bridge